### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Bugjudger** [SUPER-TADORY/1p-frac#1]
Congratulations for your great job (Scaling Backwards: Minimal Synthetic Pre-training?)!  When will you release the whole code in Github? Thanks for your attention. Looking forward your relpy!

**Comment by atztao** [comment]
Amazing the datasets.

**Comment by SUPER-TADORY** [comment]
@Bugjudger 
Thank you for your interest in our research. We plan to release the code in about 2 weeks. We apologize for the inconvenience and appreciate your understanding.

**Comment by Bugjudger** [comment]
Appreciate your rapid reply! Awesome work！
